name: Deploy and configure Kubernetes in Azure with Terraform

on:
  push:
    branches:
    - main

jobs:
  setup-install:
    name: Setup, Install
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: "Setup Terraform"
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Init 
      run: |-
        terraform init -backend-config="backend.tfvars"

    - name: Terraform Validate
      run: |-
        terraform validate

    - name: Terraform Plan
      run: |-
        terraform plan --var-file=vars.tfvars -out=plan.tfdata

    - name: Terraform Apply
      run: |-
        terraform apply -auto-approve plan.tfdata

#    - name: Terraform Destroy
#      run: |-
#        terraform destroy -auto-approve --var-file=vars.tfvars